activation: silu
aggr: add
atom_filter: -1
attn_activation: silu
batch_size: 20
coord_files: null
cutoff_lower: 0.0
cutoff_upper: 1.0
dataset: MDCustom
dataset_arg:
 root:  /home/amir/Projects/Butene_MD
 start: 1
 end: 15000
dataset_root: ~/data
derivative: true
distance_influence: both
early_stopping_patience: 300
ema_alpha_neg_dy: 1.0
ema_alpha_y: 0.05
embed_files: null
embedding_dimension: 256
energy_files: null
y_weight: 0.2
force_files: null
neg_dy_weight: 0.8
load_model: null
log_dir: logs/MLP-MD_Butene
lr: 0.001
lr_factor: 0.2
lr_min: 1.0e-07
lr_patience: 30
lr_warmup_steps: 1000
max_num_neighbors: 50000
max_z: 100
model: mlp_deepset
n_atom_basis: 22
base_cutoff: 0.0
inner_cutoff: 1.2
outer_cutoff: 2.5
triplets_cutoff: 15.0
use_vector_representation: true
forces_based_on_energy: false
close_far_split: true
using_triplet_module: false
mlp_layer: 4
neighbor_embedding: true
pairwise_thread: true
triples_thread: false
return_vecs: true
loop: true
long_edge_index: true
check_errors: false
ngpus: -1
num_epochs: 300
num_heads: 8
num_layers: 6
num_nodes: 1
num_rbf: 32
num_workers: 8
output_model: Scalar
precision: 32
prior_model: null
rbf_type: expnorm
redirect: false
reduce_op: add
save_interval: 10
splits: null
standardize: true
test_interval: 10
test_size: 100
train_size: 1000
trainable_rbf: false
val_size: 100
weight_decay: 0.0
box_vecs: null
charge: false
spin: false
vector_cutoff: true
wandb_use: false
wandb_project: Butene
tensorboard_use: true
wandb_name: Butene_MLP
